

SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'A%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/A.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'B%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/B.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'C%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/C.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'D%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/D.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'E%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/E.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'F%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/F.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'G%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/G.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'H%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/H.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'I%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/I.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'J%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/J.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'K%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/K.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'L%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/L.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'M%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/M.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'N%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/N.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'O%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/O.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'P%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/P.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'Q%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/Q.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'R%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/R.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'S%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/S.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'T%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/T.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'U%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/U.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'V%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/V.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'W%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/W.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'X%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/X.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'Y%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/Y.json';
SELECT "{" UNION ALL SELECT IF(effective="",CONCAT("""",REPLACE(postcode," ",""),""":"""","),CONCAT("""",REPLACE(postcode," ",""),""":{""A"":""",AREA,""",""E"":""",effective,"""},")) FROM uk WHERE postcode LIKE 'Z%' UNION ALL SELECT "}" INTO OUTFILE 'C:/devserver/LCDATA/new/Z.json';